x-def-logging: &default-logging
  logging:
    driver: "loki"
    options:
      loki-url: "http://localhost:3100/loki/api/v1/push"
      loki-batch-size: "100"
      loki-retries: 2
      loki-max-backoff: 1000ms
      loki-timeout: 1s

services:
  nginx:
    restart: always
    container_name: nginx
    image: nginx
    environment:
      - TZ=Asia/Almaty
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf
      - static-volume:/app/var/static
    <<: *default-logging
    networks:
      - midka-net

  django: &django
    container_name: django-1
    restart: always
    build:
      context: ./e-commerce/
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Almaty
    env_file:
      - ./e-commerce/.env
    volumes:
      - static-volume:/app/var/static
      - ./e-commerce:/app
    depends_on:
      - postgres-master
      - redis
    <<: *default-logging
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 50M
        limits:
          cpus: '1'
          memory: 100M
    networks:
      - midka-net

  django-2:
    container_name: django-2
    <<: *django

  django-3:
    container_name: django-3
    <<: *django

  celery_worker:
    restart: always
    container_name: "celery_worker"
    build:
      context: ./notification-center/
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Almaty
    depends_on:
      - django
    <<: *default-logging
    networks:
      - midka-net


  # to configure master
  # createuser --replication -P repluser
  postgres-master:
    restart: always
    container_name: "postgres-master"
    image: postgres:17.0-alpine3.20
    user: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "midka"
      TZ: "Almaty/Asia"
    <<: *default-logging
    networks:
      - midka-net
    volumes:
      - postgres-master-data:/var/lib/postgresql/data
      - ./postgresql/master/postgres.conf:/var/lib/postgresql/data/postgres.conf
      - ./postgresql/master/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf

  # to configure slave
  # rm -r ~/data/*¬
  # pg_basebackup --host=postgresql_01 --username=repluser --pgdata=/var/lib/postgresql/data --wal-method=stream --write-recovery-conf
  postgres-slave:
    container_name: "postgres-slave"
    restart: always
    image: postgres:17.0-alpine3.20
    user: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      TZ: "Almaty/Asia"
    volumes:
      - postgres-slave-data:/var/lib/postgresql/data
      - ./postgresql/slave/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    <<: *default-logging
    networks:
      - midka-net

  redis:
    restart: always
    container_name: "redis"
    image: redis:7.4.0
    <<: *default-logging
    networks:
      - midka-net

  rabbitmq:
    restart: always
    container_name: "rabbitmq"
    image: rabbitmq:4.0.2-management
    <<: *default-logging
    ports:
      - "15672:15672" # front
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    networks:
      - midka-net

  grafana:
    container_name: "grafana"
    restart: unless-stopped
    user: "0"
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - TERM=linux
      - GF_SERVER_ROOT_URL=http://my.grafana.server/
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-polystat-panel
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - TZ=Asia/Almaty
    networks:
      - midka-net

  loki:
    hostname: loki
    image: grafana/loki:latest
    environment:
      TZ: "Almaty/Asia"
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/retention-config.yaml
    volumes:
      - ./loki/config.yaml:/etc/loki/retention-config.yaml
    networks:
      - midka-net

volumes:
  postgres-master-data:
  static-volume:
  postgres-slave-data:
  grafana-data:

networks:
  midka-net:
    external: true